[package]
name = "cursmetic_recognizer"
version = "0.1.0"
edition = "2024"

[dependencies]
icu_segmenter = "2.3.0"
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.20"
unicode-normalization = "0.1.25"
windows = { version = "0.62.2", features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation"
] }
